---
title: "????????????DEG??????"
author: "jmzeng@163.com"
date: "10/16/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
 
# ????????????????????????
```{r}
suppressPackageStartupMessages(library(airway))
suppressPackageStartupMessages(library(DESeq))
suppressPackageStartupMessages(library(limma))
suppressPackageStartupMessages(library(DESeq2))
suppressPackageStartupMessages(library(edgeR)) 
suppressPackageStartupMessages(library(pasilla))
suppressPackageStartupMessages(library(pasilla))
suppressPackageStartupMessages(library(Biobase))
suppressPackageStartupMessages(library(CLL))
```
# ???????????????????????????
```{r}
## ????????????????????????????????????????????????ExpressionSet??????
data(sCLLex)
## hgu95av2???????????????????????????14????????????8?????????
data(pasillaGenes) 
## ?????????3?????????????????????4???,????????????counts??????
data(airway)
## RangedSummarizedExperiment????????????assay(airway)???????????????????????? colData ???rowData??????????????????????????????

## ???????????????????????????4????????????,????????????counts??????
```


# ???????????????normalization

???????????? scater ??? DESeq2?????????????????????reads counts??????????????????

```{r}
exprSet=assay(airway) # 64102 ????????????8????????????????????????
## ?????????????????????????????????
geneLists=row.names(exprSet)
keepGene=rowSums(edgeR::cpm(exprSet)>0) >=2
table(keepGene);dim(exprSet)
dim(exprSet[keepGene,])
exprSet=exprSet[keepGene,]
rownames(exprSet)=geneLists[keepGene]

group_list=colData(airway)$dex
(colData <- data.frame(row.names=colnames(exprSet), group_list=group_list) )
dds <- DESeqDataSetFromMatrix(countData = exprSet,
                              colData = colData,
                              design = ~ group_list)
dds <- DESeq(dds) 
plotDispEsts(dds, main="Dispersion plot") 

rld <- rlogTransformation(dds)
exprMatrix_rlog=assay(rld) 

normalizedCounts1 <- t( t(counts(dds)) / sizeFactors(dds) )
exprMatrix_rpm=as.data.frame(normalizedCounts1) 
head(exprMatrix_rpm) 

library(scater)
pheno_data <- new("AnnotatedDataFrame", colData) 
dat <- scater::newSCESet(
  countData = exprSet,
  phenoData = pheno_data
)
dat_qc <- scater::calculateQCMetrics(dat)
set_exprs(dat_qc, "log2_counts") <- log2(counts(dat) + 1)
dat_qc <- normaliseExprs(
  dat_qc,
  method = "TMM" 
)
exprMatrix_tmm=norm_exprs(dat_qc)
dat_qc <- normaliseExprs(
  dat_qc,
  method = "RLE" 
)
exprMatrix_rle=norm_exprs(dat_qc)
exprMatrix_scater=exprs(dat_qc)
exprMatrix_log2_counts=get_exprs(dat_qc,'log2_counts')
```

# ?????????????????????

```{r}
boxplot(exprMatrix_rpm,las=2)
boxplot(exprMatrix_log2_counts,las=2)

boxplot(exprMatrix_rle,las=2)
boxplot(exprMatrix_rlog,las=2)

boxplot(exprMatrix_scater,las=2)
boxplot(exprMatrix_tmm,las=2)
```

??????????????????reads counts?????????????????????????????????????????????????????????????????????normalization?????????????????????log2???????????????????????????????????????????????????????????????rle,rlog?????????normalization?????????

# ????????????

## ??????T??????

```{r}
      dat = exprMatrix_rlog 
      ## ????????????DESeq2????????????????????????
      group1 = which(group_list == levels(group_list)[1])
      group2 = which(group_list == levels(group_list)[2])
      dat1 = dat[, group1]
      dat2 = dat[, group2]
      dat = cbind(dat1, dat2) 
      library(pi0)
      pvals = matrix.t.test(dat, 1, 
               length(group1), length(group2))
      p.adj = p.adjust(pvals, method = "BH")
      avg_1 = rowMeans(dat1)
      avg_2 = rowMeans(dat2)
      FC = avg_2/avg_1
      results = cbind(avg_1, avg_2, FC, pvals, p.adj)
      colnames(results) = c("avg_1", "avg_2", "logFC", "P.Value", "adj.P.Val") 
      rlog_t_test_DEG=results
```

## ?????? ks ??????

```{r}
dat = exprMatrix_rlog 
## ????????????DESeq2????????????????????????
group1 = which(group_list == levels(group_list)[1])
group2 = which(group_list == levels(group_list)[2])
dat1 = dat[, group1]
dat2 = dat[, group2]
dat = cbind(dat1, dat2) 
library(pi0)
pvals =  apply(exprMatrix_rlog, 1, function(x) {
  ks.test(x[group1], 
          x[group2])$p.value
   })
p.adj = p.adjust(pvals, method = "BH")
avg_1 = rowMeans(dat1)
avg_2 = rowMeans(dat2)
FC = avg_2/avg_1
results = cbind(avg_1, avg_2, FC, pvals, p.adj)
colnames(results) = c("avg_1", "avg_2", "logFC", "P.Value", "adj.P.Val") 
rlog_ks_test_DEG=results
```


## ?????? DESeq2 ???

```{r}
  res <- results(dds, contrast=c("group_list","trt","untrt"))
  resOrdered <- res[order(res$padj),]
  head(resOrdered)
  DESeq2_DEG=as.data.frame(resOrdered)
```


## ?????? edgeR ???

```{r}
library(edgeR)
d <- DGEList(counts=exprSet,group=factor(group_list))
d$samples$lib.size <- colSums(d$counts)
d <- calcNormFactors(d)
d$samples 
dge=d

design <- model.matrix(~0+factor(group_list))
rownames(design)<-colnames(dge)
colnames(design)<-levels(factor(group_list))

dge <- estimateGLMCommonDisp(dge,design)
dge <- estimateGLMTrendedDisp(dge, design)
dge <- estimateGLMTagwiseDisp(dge, design)

fit <- glmFit(dge, design)

lrt <- glmLRT(fit,  contrast=c(-1,1))
nrDEG=topTags(lrt, n=nrow(exprSet))
nrDEG=as.data.frame(nrDEG)
head(nrDEG)
edgeR_DEG=nrDEG
```

## ??????P?????????

```{r}
p_dat = data.frame(
  t=rlog_t_test_DEG[,4],
  deseq2=DESeq2_DEG[rownames(rlog_t_test_DEG),5],
  edgeR=edgeR_DEG[rownames(rlog_t_test_DEG),4]
)
p_dat = na.omit(p_dat )
cor(p_dat)
```

 
 
 